# see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
# 
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  - init: ./refine build
    command: ./refine -H "*" run

ports:
  - port: 3333
